# Generated by Django 4.0.1 on 2022-02-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='', max_length=500, null=True)),
                ('lastname', models.CharField(default='', max_length=200, null=True)),
                ('username', models.CharField(default='', max_length=200, null=True)),
                ('email', models.EmailField(default='', max_length=200, null=True)),
                ('password', models.CharField(default='', max_length=200, null=True)),
                ('courcenames', models.CharField(default='', max_length=200, null=True)),
                ('courceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cource3')),
            ],
        ),
    ]
