# Generated by Django 4.0.1 on 2022-02-13 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cource3',
            fields=[
                ('courceid', models.AutoField(primary_key=True, serialize=False)),
                ('courcenames', models.CharField(default='', max_length=200, null=True)),
                ('coursedsp', models.CharField(default='', max_length=200, null=True)),
                ('coursemodules', models.CharField(default='', max_length=200, null=True)),
                ('courselevel', models.CharField(default='', max_length=200, null=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('tutorialid', models.AutoField(primary_key=True, serialize=False)),
                ('videoname', models.CharField(default='', max_length=200, null=True)),
                ('videodsp', models.CharField(default='', max_length=2000, null=True)),
                ('videos', models.FileField(null=True, upload_to='video')),
                ('courceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cource3')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('questionsid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=500, null=True)),
                ('option1', models.CharField(default='', max_length=200, null=True)),
                ('option2', models.CharField(default='', max_length=200, null=True)),
                ('option3', models.CharField(default='', max_length=200, null=True)),
                ('answers', models.CharField(default='', max_length=200, null=True)),
                ('courceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cource3')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tutorialid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tutorial')),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('platformid', models.AutoField(primary_key=True, serialize=False)),
                ('platformname', models.CharField(default='', max_length=255, null=True)),
                ('platformdsp', models.CharField(default='', max_length=2055, null=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cource3',
            name='platformid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.platform'),
        ),
    ]
